



-- 1. 사용자 테이블 목록 조회하기
SELECT * FROM TABS

-- 2. 전체 데이터 조회하기
SELECT
    REGIONID
    ,PRODUCTGROUP
    ,YEARWEEK
    ,VOLUME
    FROM KOPO_PRODUCT_VOLUME
    
-- 3. Expression 이용하기
SELECT
    '201701_BATCH' AS PLANID
    ,'KOPO_D510' AS MEASUREID
    ,REGIONID||'_'||PRODUCTGROUP AS ID
    FROM KOPO_PRODUCT_VOLUME

-- 4. 중복된 값 제거하기(DISTINCT)
SELECT 
    DISTINCT REGIONID
    ,PRODUCTGROUP
    FROM KOPO_PRODUCT_VOLUME
    
-- 5. 조건절 (WHERE) 사용하기
SELECT 
    *
    FROM KOPO_PRODUCT_VOLUME
    WHERE 1=1
    AND PRODUCTGROUP = 'ST0002'
    AND YEARWEEK IN ('201515','201516')

SELECT 
    *
    FROM KOPO_PRODUCT_VOLUME
    WHERE 1=1
    AND PRODUCTGROUP = 'ST0002'
    AND YEARWEEK > 201514
    AND YEARWEEK < 201517

SELECT 
    *
    FROM KOPO_PRODUCT_VOLUME
    WHERE 1=1
    AND PRODUCTGROUP = 'ST0002'
    AND (YEARWEEK = '201515'
        OR YEARWEEK = '201516')
        
-- 6. 산술연산자 사용하기
-- https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions001.htm
SELECT 
    ROUND(PMAP * 0.9, 0) AS PRICE
    FROM KOPO_PROMOTION
    
SELECT     
    CASE WHEN MAP_PRICE = 0
        THEN 1
        ELSE PMAP/NVL(MAP_PRICE, PMAP)
        END AS PRO_PERCENT
    FROM KOPO_PROMOTION
    
-- 7. 기타 연산자 리스트
SELECT 
        *
        FROM KOPO_PRODUCT_VOLUME
        WHERE 1=1
        AND PRODUCTGROUP = 'ST0001'
        AND YEARWEEK BETWEEN '201544' AND '201548'
    
-- 8. 검색조건 (AND/OR) 사용
SELECT 
    *
    FROM KOPO_PRODUCT_VOLUME
    WHERE 1=1
    AND PRODUCTGROUP = 'ST0002'
    AND (YEARWEEK = '201515'
        OR YEARWEEK = '201516')